Repository Daniel-Froes/Animepedia, pull requests merged in 2022-06, with the labels that each got.

#53 feat: finalizando a page de admin
  Back-end/app.js
  Back-end/controllers/aprovarController.js
  Back-end/controllers/usuariosController.js
  Back-end/controllers/vipsController.js
  Back-end/routes/aprovar.js
  Back-end/routes/usuarios.js
  Back-end/routes/vips.js
  Back-end/views/aprovar.ejs
  Back-end/views/index.ejs
  Back-end/views/usuarios.ejs
  Back-end/views/vips.ejs
  package-lock.json
  server/views/aot.ejs
Labels: documentation, enhancement

#56 feat: finalizando pagina de admin
  Back-end/app.js
  Back-end/controllers/adminController.js
  Back-end/controllers/aprovarController.js
  Back-end/controllers/criarPostController.js
  Back-end/controllers/usuariosController.js
  Back-end/controllers/vipsController.js
  Back-end/routes/admin.js
  Back-end/routes/aprovar.js
  Back-end/routes/criarPost.js
  Back-end/routes/users.js
  Back-end/routes/usuarios.js
  Back-end/views/admin.ejs
  Back-end/views/partials/header.ejs
  Back-end/views/partials/headerAdmin.ejs
  Back-end/views/vips.ejs
Labels: documentation, enhancement

#57 feat: adicionando react ao projeto
  animepedia/.eslintrc.json
  animepedia/.gitignore
  animepedia/README.md
  animepedia/next-env.d.ts
  animepedia/next.config.js
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/pages/_app.tsx
  animepedia/pages/api/hello.ts
  animepedia/pages/index.tsx
  animepedia/public/favicon.ico
  animepedia/public/vercel.svg
  animepedia/styles/Home.module.css
  animepedia/styles/globals.css
  animepedia/tsconfig.json
Labels: enhancement

#58 feat: arrumando pagina de login
  Back-end/app.js
  Back-end/public/sass/cadastroStyle.scss
  Back-end/public/sass/categoriaStyle.scss
  Back-end/public/stylesheets/bundle.css
  Back-end/views/cadastro.ejs
  Back-end/views/categorias.ejs
  Back-end/views/partials/footerRegister.ejs
Labels: enhancement

#59 Feat/news
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/pages/api/hello.ts
  animepedia/pages/index.tsx
  animepedia/public/favicon.ico
  animepedia/public/styles/globals.css
  animepedia/public/vercel.svg
  animepedia/src/pages/_app.tsx
  animepedia/src/pages/index.tsx
  animepedia/styles/Home.module.css
Labels: bug, documentation
