Repository Daniel-Froes/Animepedia, pull requests merged in 2022-05, with the labels that each got.

#1 Feat/features
  anime/main.html
  assets/bootstrap/css/bootstrap.min.css
  assets/css/Inter.css
  assets/css/Navbar-Centered-Links.css
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7SUc.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7SUc.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7SUc.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7SUc.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7SUc.woff2
  assets/fonts/s/inter/v11/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2
  assets/img/team/avatar2.jpg
  assets/img/team/avatar4.jpg
  assets/img/team/avatar5.jpg
  assets/js/bold-and-bright.js
  assets/js/bs-init.js
  index.html
  package.json
Labels: documentation, enhancement

#10 feat: arrumando navbar
  index.html
  screens/index.html
  styles/_custom_colors.scss
  styles/indexStyle.css
  styles/indexStyle.scss
Labels: enhancement, good first issue

#12 Feat/features
  sass/_custom_colors.scss
  sass/indexStyle.scss
  screens/index.html
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: documentation, enhancement

#13 feat: arrumando menu hamburguer
  sass/indexStyle.scss
  screens/index.html
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: enhancement, good first issue

#15 feat: arrumando os cards e o footer
  sass/indexStyle.scss
  screens/cadastro.html
  screens/index.html
  screens/login.html
  screens/noticia.html
  src/img/chainsawman.jpg
  src/img/fujiwara.jpg
  src/img/kaguyasamatemp3.jpg
  src/img/kitagawamarin.png
  src/img/kizumimonogatari.jpg
  src/img/kizumonogatari1.jpg
  src/img/shikimori.jpg
  src/img/shinobu.jpg
  src/img/spyfamilia.png
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: enhancement, good first issue

#16 feat: arrumando bota de login
  sass/indexStyle.scss
  screens/index.html
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: enhancement, good first issue

#20 Feat/features
  screens/cadastro.html
Labels: documentation, duplicate, enhancement

#22 Feat/features
  sass/indexStyle.scss
  screens/index.html
  src/Fonts/Itacha.ttf
  src/img/AnimepediaTitulo.png
  src/img/img-nav.png
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: documentation, duplicate

#23 feat: add page cadastro
  sass/cadastroStyle.scss
  screens/cadastro.html
  styles/cadastroStyle.css
  styles/cadastroStyle.css.map
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: documentation, enhancement

#24 feat: add page login
  sass/loginStyle.scss
  screens/login.html
  styles/loginStyle.css
  styles/loginStyle.css.map
Labels: documentation, enhancement

#26 feat: add page anime
  sass/animeStyle.scss
  screens/Anime.html
  screens/cadastro.html
  screens/login.html
  src/img/snk.jpg
  styles/animeStyle.css
  styles/animeStyle.css.map
Labels: documentation, enhancement

#27 Feat/features
  screens/Anime.html
  screens/cadastro.html
  screens/index.html
  screens/login.html
Labels: duplicate, enhancement, good first issue

#28 feat: arrumando card anime
  sass/animeStyle.scss
  screens/Anime.html
  styles/animeStyle.css
  styles/animeStyle.css.map
Labels: documentation, duplicate, enhancement

#29 Feat/features
  js/carrossel.js
  js/glider.min.js
  sass/indexStyle.scss
  screens/Anime.html
  screens/index.html
  styles/glider.min.css
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: duplicate, enhancement, good first issue

#30 feat: arrumando responsividade no carrossel
  js/carrossel.js
  sass/indexStyle.scss
  screens/index.html
  src/img/nagatorotrailer.jpg
  src/img/officialtrailer.jpg
  styles/indexStyle.css
  styles/indexStyle.css.map
Labels: enhancement, good first issue

#31 feat: add page animes
  screens/Anime.html
Labels: documentation, enhancement

#32 feat:arrumando tamanho do texto
  sass/animeStyle.scss
  screens/Anime.html
  styles/animeStyle.css
  styles/animeStyle.css.map
Labels: enhancement, good first issue

#33 feat: add cards recomendados
  screens/Anime.html
  src/img/The-Promised-Neverland.jpg
  src/img/death-parade.jpg
  src/img/erased.jpg
  src/img/made-in-abyss.jpg
Labels: documentation, enhancement

#34 fix: arrumando carrosel page categorias
  js/carrosel-categoria.js
  sass/categoria.scss
  screens/categoria.html
  styles/categoria.css
  styles/categoria.css.map
Labels: bug, documentation

#35 Feat/features
  README.md
  js/carrosel-categoria.js
  js/carrossel.js
  sass/_custom_colors.scss
  sass/animeStyle.scss
  screens/Anime.html
  screens/categoria.html
  styles/animeStyle.css
  styles/animeStyle.css.map
Labels: bug, enhancement

#36 Feat/features
  js/anime-recomendacoes.js
  js/carrossel-categoria.js
  sass/animeStyle.scss
  screens/Anime.html
  screens/categoria.html
  styles/animeStyle.css
  styles/animeStyle.css.map
Labels: documentation, enhancement

#37 fix: carrosel categorias
  screens/categoria.html
Labels: bug, documentation

#38 feat: arrumando carrossel do categoria
  js/carrossel-categoria.js
  sass/categoriaStyle.scss
  screens/categoria.html
  src/img/albedo overlord.jpg
  styles/categoriaStyle.css
  styles/categoriaStyle.css.map
Labels: documentation, enhancement

#39 feat: arrumando bugs do carrossel
  js/carrossel-categoria.js
  sass/categoriaStyle.scss
  screens/categoria.html
  styles/categoriaStyle.css
  styles/categoriaStyle.css.map
Labels: documentation, enhancement

#40 feat: adicionando express generator
  animepedia/app.js
  animepedia/bin/www
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/public/stylesheets/style.css
  animepedia/routes/index.js
  animepedia/routes/users.js
  animepedia/views/error.ejs
  animepedia/views/index.ejs
Labels: documentation, enhancement

#42 feat: adicionando gulp ao projeto
  server/gulpfile.js
  server/package-lock.json
  server/package.json
  server/public/stylesheets/animeStyle.css
  server/public/stylesheets/cadastroStyle.css
  server/public/stylesheets/categoriaStyle.css
  server/public/stylesheets/indexStyle.css
  server/public/stylesheets/loginStyle.css
  server/sass/animeStyle.scss
  server/views/Anime.ejs
Labels: documentation, enhancement

#43 feat: configurando o gulp
  server/gulpfile.js
  server/package-lock.json
  server/package.json
  server/public/stylesheets/animeStyle.css
  server/public/stylesheets/bundle.css
  server/public/stylesheets/cadastroStyle.css
  server/public/stylesheets/categoriaStyle.css
  server/public/stylesheets/indexStyle.css
  server/public/stylesheets/loginStyle.css
Labels: bug, documentation, enhancement

#44 fix: bug nos arquivos
  server/package-lock.json
  server/package.json
  server/public/stylesheets/animeStyle.css
  server/public/stylesheets/animeStyle.css.map
  server/public/stylesheets/bundle.css
  server/public/stylesheets/cadastroStyle.css
  server/public/stylesheets/cadastroStyle.css.map
  server/public/stylesheets/categoria.css
  server/public/stylesheets/categoria.css.map
  server/public/stylesheets/categoriaStyle.css
  server/public/stylesheets/categoriaStyle.css.map
  server/public/stylesheets/indexStyle.css
  server/public/stylesheets/indexStyle.css.map
  server/public/stylesheets/loginStyle.css
  server/public/stylesheets/loginStyle.css.map
  server/public/stylesheets/style.css
  server/sass/animeStyle.scss
  server/views/Anime.ejs
Labels: bug

#45 feat: add page partials
  server/views/partials/footer.ejs
  server/views/partials/head.ejs
  server/views/partials/header.ejs
Labels: documentation, enhancement

#46 fix: arrumando bug do back end
  Front-end/.gitignore
  Front-end/LICENSE
  Front-end/README.md
  Front-end/js/anime-recomendacoes.js
  Front-end/js/carrossel-categoria.js
  Front-end/js/carrossel.js
  Front-end/js/glider.min.js
  Front-end/js/index.js
  Front-end/package-lock.json
  Front-end/package.json
  Front-end/sass/_custom_colors.scss
  Front-end/sass/animeStyle.scss
  Front-end/sass/cadastroStyle.scss
  Front-end/sass/categoriaStyle.scss
  Front-end/sass/indexStyle.scss
  Front-end/sass/loginStyle.scss
  Front-end/screens/Anime.html
  Front-end/screens/cadastro.html
  Front-end/screens/categoria.html
  Front-end/screens/index.html
  Front-end/screens/login.html
  Front-end/src/Fonts/Itacha.ttf
  Front-end/src/img/AnimepediaTitulo.png
  Front-end/src/img/The-Promised-Neverland.jpg
  Front-end/src/img/albedo overlord.jpg
  Front-end/src/img/chainsawman.jpg
  Front-end/src/img/death-parade.jpg
  Front-end/src/img/erased.jpg
  Front-end/src/img/favicon.ico
  Front-end/src/img/fujiwara.jpg
  Front-end/src/img/img-nav.png
  Front-end/src/img/kaguyasamatemp3.jpg
  Front-end/src/img/kitagawamarin.png
  Front-end/src/img/kizumimonogatari.jpg
  Front-end/src/img/kizumonogatari1.jpg
  Front-end/src/img/made-in-abyss.jpg
  Front-end/src/img/nagatorotrailer.jpg
  Front-end/src/img/officialtrailer.jpg
  Front-end/src/img/shikimori.jpg
  Front-end/src/img/shinobu.jpg
  Front-end/src/img/snk.jpg
  Front-end/src/img/spyfamilia.png
  Front-end/src/img/thumb-haikyu.jpg
  Front-end/src/img/thumb-pnv.png
  Front-end/src/img/thumb-snk.png
  Front-end/src/img/thumb-spy.png
  Front-end/styles/animeStyle.css
  Front-end/styles/animeStyle.css.map
  Front-end/styles/cadastroStyle.css
  Front-end/styles/cadastroStyle.css.map
  Front-end/styles/categoria.css
  Front-end/styles/categoria.css.map
  Front-end/styles/categoriaStyle.css
  Front-end/styles/categoriaStyle.css.map
  Front-end/styles/glider.min.css
  Front-end/styles/indexStyle.css
  Front-end/styles/indexStyle.css.map
  Front-end/styles/loginStyle.css
  Front-end/styles/loginStyle.css.map
Labels: bug

#49 Feat/news
  Back-end/app.js
  Back-end/controllers/categoriaController.js
  Back-end/gulpfile.js
  Back-end/package-lock.json
  Back-end/package.json
  Back-end/public/fonts/Itacha.ttf
  Back-end/public/images/AnimepediaTitulo.png
  Back-end/public/images/The-Promised-Neverland.jpg
  Back-end/public/images/albedo overlord.jpg
  Back-end/public/images/chainsawman.jpg
  Back-end/public/images/death-parade.jpg
  Back-end/public/images/erased.jpg
  Back-end/public/images/favicon.ico
  Back-end/public/images/fujiwara.jpg
  Back-end/public/images/img-nav.png
  Back-end/public/images/kaguyasamatemp3.jpg
  Back-end/public/images/kitagawamarin.png
  Back-end/public/images/kizumimonogatari.jpg
  Back-end/public/images/kizumonogatari1.jpg
  Back-end/public/images/made-in-abyss.jpg
  Back-end/public/images/nagatorotrailer.jpg
  Back-end/public/images/officialtrailer.jpg
  Back-end/public/images/shikimori.jpg
  Back-end/public/images/shinobu.jpg
  Back-end/public/images/snk.jpg
  Back-end/public/images/spyfamilia.png
  Back-end/public/images/thumb-haikyu.jpg
  Back-end/public/images/thumb-pnv.png
  Back-end/public/images/thumb-snk.png
  Back-end/public/images/thumb-spy.png
  Back-end/public/javascripts/anime-recomendacoes.js
  Back-end/public/javascripts/carrossel-categoria.js
  Back-end/public/javascripts/carrossel.js
  Back-end/public/javascripts/glider.min.js
  Back-end/public/javascripts/index.js
  Back-end/public/sass/_custom_colors.scss
  Back-end/public/sass/animeStyle.scss
  Back-end/public/sass/cadastroStyle.scss
  Back-end/public/sass/categoriaStyle.scss
  Back-end/public/sass/indexStyle.scss
  Back-end/public/sass/loginStyle.scss
  Back-end/public/stylesheets/bundle.css
  Back-end/public/stylesheets/glider.min.css
  Back-end/public/stylesheets/style.css
  Back-end/routes/categoria.js
  Back-end/views/categoria.ejs
  Back-end/views/partials/footer.ejs
  Back-end/views/partials/head.ejs
  Back-end/views/partials/header.ejs
  Back-end/views/post.ejs
Labels: documentation, enhancement

#50 Feat/news
  Back-end/controllers/categoriaController.js
  Back-end/public/sass/cadastroStyle.scss
  Back-end/public/sass/loginStyle.scss
  Back-end/public/stylesheets/animeStyle.css
  Back-end/public/stylesheets/bundle.css
  Back-end/public/stylesheets/cadastroStyle.css
  Back-end/public/stylesheets/categoriaStyle.css
  Back-end/public/stylesheets/indexStyle.css
  Back-end/public/stylesheets/loginStyle.css
  Back-end/public/stylesheets/style.css
  Back-end/views/categoria.ejs
  Back-end/views/partials/footer.ejs
  Back-end/views/partials/head.ejs
  Back-end/views/partials/header.ejs
Labels: documentation, enhancement
