Repository Daniel-Froes/Animepedia, pull requests merged in 2022-07, with the labels that each got.

#61 feat: arrumando o gulp
  animepedia/.eslintrc.json
  animepedia/gulpfile.js
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/public/fonts/Itacha.ttf
  animepedia/public/images/AnimepediaTitulo.png
  animepedia/public/images/The-Promised-Neverland.jpg
  animepedia/public/images/albedo overlord.jpg
  animepedia/public/images/chainsawman.jpg
  animepedia/public/images/death-parade.jpg
  animepedia/public/images/erased.jpg
  animepedia/public/images/favicon.ico
  animepedia/public/images/fujiwara.jpg
  animepedia/public/images/img-nav.png
  animepedia/public/images/kaguyasamatemp3.jpg
  animepedia/public/images/kitagawamarin.png
  animepedia/public/images/kizumimonogatari.jpg
  animepedia/public/images/kizumonogatari1.jpg
  animepedia/public/images/made-in-abyss.jpg
  animepedia/public/images/nagatorotrailer.jpg
  animepedia/public/images/officialtrailer.jpg
  animepedia/public/images/shikimori.jpg
  animepedia/public/images/shinobu.jpg
  animepedia/public/images/snk.jpg
  animepedia/public/images/spyfamilia.png
  animepedia/public/images/thumb-haikyu.jpg
  animepedia/public/images/thumb-pnv.png
  animepedia/public/images/thumb-snk.png
  animepedia/public/images/thumb-spy.png
  animepedia/public/javascripts/anime-recomendacoes.js
  animepedia/public/javascripts/carrossel-categoria.js
  animepedia/public/javascripts/carrossel.js
  animepedia/public/javascripts/glider.min.js
  animepedia/public/javascripts/index.js
  animepedia/public/sass/_custom_colors.scss
  animepedia/public/sass/animeStyle.scss
  animepedia/public/sass/cadastroStyle.scss
  animepedia/public/sass/categoriaStyle.scss
  animepedia/public/sass/indexStyle.scss
  animepedia/public/sass/loginStyle.scss
  animepedia/src/pages/_app.tsx
  animepedia/src/pages/index.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/styles/glider.min.css
  animepedia/src/ui/components/categoria/categoria.tsx
  animepedia/src/ui/components/header/header.tsx
Labels: enhancement

#62 feat: adicionando componentes react
  animepedia/package-lock.json
  animepedia/src/pages/index.tsx
  animepedia/src/ui/components/footer/footer.tsx
  animepedia/src/ui/components/slider/sliderCategory.tsx
Labels: documentation, enhancement

#63 feat: arrumando o header component
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/public/sass/animeStyle.scss
  animepedia/public/sass/cadastroStyle.scss
  animepedia/public/sass/categoriaStyle.scss
  animepedia/public/sass/indexStyle.scss
  animepedia/public/sass/loginStyle.scss
  animepedia/src/pages/_app.tsx
  animepedia/src/pages/index.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/styles/globals.css
  animepedia/src/ui/components/header/header.tsx
Labels: enhancement

#64 feat: arrumando font family
  animepedia/public/fonts/Zenzai Itacha.woff
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/index.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/footer/footer.tsx
Labels: enhancement

#65 feat: adicionando menus dropdown
  animepedia/src/ui/components/header/header.tsx
Labels: documentation, enhancement

#66 Feat/news
  Back-end/gulpfile.js
  Back-end/views/partials/header.ejs
  Front-end/sass/animeStyle.scss
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/public/javascripts/carrossel.js
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/index.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/categoria/categoria.tsx
  animepedia/src/ui/components/footer/footer.tsx
  animepedia/src/ui/components/header/header.tsx
  animepedia/src/ui/components/index/index.tsx
  animepedia/src/ui/components/sliderCategory/sliderCategory.tsx
  animepedia/src/ui/components/sliderCategory/sliderIndex.tsx
  package.json
Labels: enhancement

#67 feat: arrumando pastas
  animepedia/src/ui/components/category/category.tsx
  animepedia/src/ui/components/category/sliderCategory.tsx
  animepedia/src/ui/components/index/sliderIndex.tsx
Labels: enhancement

#68 feat: arrumando slider
  animepedia/public/images/albedoOverlord.jpg
  animepedia/src/pages/index.tsx
  animepedia/src/ui/components/category/sliderCategory.tsx
  animepedia/src/ui/components/index/card.tsx
  animepedia/src/ui/components/index/index.tsx
  animepedia/src/ui/components/index/sliderNews.tsx
Labels: enhancement

#69 feat: adicionando componente de cards
  animepedia/src/pages/index.tsx
  animepedia/src/ui/components/card/cardGrid.tsx
Labels: documentation, enhancement

#73 feat:arrumando pages e pastas
  animepedia/public/javascripts/anime-recomendacoes.js
  animepedia/public/javascripts/carrossel-categoria.js
  animepedia/public/javascripts/carrossel.js
  animepedia/public/javascripts/glider.min.js
  animepedia/public/javascripts/index.js
  animepedia/public/sass/cadastroStyle.scss
  animepedia/public/sass/loginStyle.scss
  animepedia/src/pages/[lc]/cadastro.tsx
  animepedia/src/pages/[lc]/login.tsx
  animepedia/src/pages/_app.tsx
  animepedia/src/pages/cadastro.tsx
  animepedia/src/pages/index.tsx
  animepedia/src/pages/login.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardGroups.tsx
  animepedia/src/ui/components/footer/footer.tsx
  animepedia/src/ui/components/forms/formCadastro.tsx
  animepedia/src/ui/components/forms/formLogin.tsx
  animepedia/src/ui/components/header/header.tsx
  animepedia/src/ui/components/index/index.tsx
  animepedia/src/ui/components/index/sliderIndex.tsx
  animepedia/src/ui/components/index/sliderNews.tsx
Labels: enhancement

#74 feature: adicionando sequelize
  .sequelizerc
  Back-end/middlewares/config/config.json
  Back-end/middlewares/models/index.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#75 fix: arrumando erro do sequelize e criando primeiro model
  .sequelizerc
  Back-end/config/config.json
  Back-end/migrations/20220714200815-create-user.js
  Back-end/models/index.js
  Back-end/models/user.js
  Back-end/package-lock.json
  Back-end/package.json
Labels: bug, documentation, enhancement

#76 Feat/news
  animepedia/public/sass/indexStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/styles/globals.css
  animepedia/src/ui/components/card/cardGroups.tsx
  animepedia/src/ui/components/index/index.tsx
Labels: enhancement

#77 feat: adicionando tabelas do backend pelo sequelize
  Back-end/migrations/20220715152551-create-anime.js
  Back-end/migrations/20220715153402-create-descricao.js
  Back-end/migrations/20220715181923-create-comentario.js
  Back-end/migrations/20220715182330-create-post.js
  Back-end/models/anime.js
  Back-end/models/comentario.js
  Back-end/models/descricao.js
  Back-end/models/post.js
  package-lock.json
Labels: documentation, enhancement

#78 feat: arrumando usuario
  Back-end/migrations/20220715182919-create-usuario.js
  Back-end/models/usuario.js
Labels: enhancement

#79 feat: adicionando relacionamento entre tabelas
  Back-end/migrations/20220714200815-create-user.js
  Back-end/models/anime.js
  Back-end/models/descricao.js
Labels: documentation, enhancement

#80 fix: apagando arquivos sequilize-cli
  Back-end/config/config.json
  Back-end/migrations/20220715152551-create-anime.js
  Back-end/migrations/20220715153402-create-descricao.js
  Back-end/migrations/20220715181923-create-comentario.js
  Back-end/migrations/20220715182330-create-post.js
  Back-end/migrations/20220715182919-create-usuario.js
  Back-end/models/anime.js
  Back-end/models/comentario.js
  Back-end/models/descricao.js
  Back-end/models/index.js
  Back-end/models/post.js
  Back-end/models/usuario.js
  Back-end/package-lock.json
  Back-end/package.json
Labels: bug

#81 fix: consertando bug sequelize
  Back-end/package-lock.json
  Back-end/package.json
Labels: bug

#82 Feat/news
  Back-end/.sequelizerc
  Back-end/config/config.json
  Back-end/migrations/20220716140132-create-usuario.js
  Back-end/migrations/20220716140239-create-anime.js
  Back-end/migrations/20220716140605-create-post.js
  Back-end/migrations/20220716140803-create-descricao.js
  Back-end/models/anime.js
  Back-end/models/descricao.js
  Back-end/models/index.js
  Back-end/models/post.js
  Back-end/models/usuario.js
  Back-end/package-lock.json
  Back-end/seeders/20220716141209-demo-user.js
Labels: enhancement
