Repository Daniel-Froes/Animepedia, pull requests merged in 2022-08, with the labels that each got.

#83 feat: adicionando page anime
  animepedia/src/pages/[lc]/anime.tsx
  animepedia/src/ui/components/anime/anime.tsx
Labels: documentation, enhancement

#84 Feat/news
  Back-end/migrations/20220716140132-create-usuario.js
  Back-end/models/index.js
  Back-end/models/usuario.js
  Back-end/package-lock.json
  Back-end/package.json
  README.md
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/src/data/services/ApiService.ts
  animepedia/src/ui/components/anime/anime.tsx
Labels: documentation, enhancement

#85 feat: terminando pagina de animes
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/public/sass/animeStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/anime/anime.tsx
Labels: documentation, enhancement

#86 feat: adicionando cores e finalizando template de anime
  animepedia/public/sass/_custom_colors.scss
  animepedia/public/sass/animeStyle.scss
  animepedia/public/sass/indexStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/anime/anime.tsx
  animepedia/src/ui/components/header/header.tsx
  animepedia/src/ui/components/index/card.tsx
Labels: documentation, enhancement

#87 feat: fazendo about pagina index
  animepedia/public/images/aa.jpg
  animepedia/public/images/bb.png
  animepedia/public/images/daniel.jfif
  animepedia/public/images/isa.jpg
  animepedia/public/images/menina.jpg
  animepedia/public/images/noite.jpg
  animepedia/public/images/nuvem.jpg
  animepedia/public/images/roxo.png
  animepedia/public/images/sla.jpg
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/[lc]/sobre.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardAbout.tsx
  animepedia/src/ui/components/footer/footer.tsx
  animepedia/src/ui/components/header/headerAbout.tsx
  animepedia/src/ui/components/index/sliderAbout.tsx
  animepedia/src/ui/components/index/sliderNews.tsx
  animepedia/src/ui/components/sobre/pageSobre.tsx
Labels: documentation, enhancement

#89 fix
  Back-end/views/admin.ejs
  Back-end/views/aprovar.ejs
  Back-end/views/cadastro.ejs
  Back-end/views/categorias.ejs
  Back-end/views/criarPost.ejs
  Back-end/views/editarPerfil.ejs
  Back-end/views/error.ejs
  Back-end/views/index.ejs
  Back-end/views/login.ejs
  Back-end/views/partials/footer.ejs
  Back-end/views/partials/footerRegister.ejs
  Back-end/views/partials/head.ejs
  Back-end/views/partials/header.ejs
  Back-end/views/partials/headerAdmin.ejs
  Back-end/views/partials/indexFooter.ejs
  Back-end/views/partials/sliderCategory.ejs
  Back-end/views/post.ejs
  Back-end/views/usuarios.ejs
  Back-end/views/vips.ejs
Labels: bug

#90 feat: isso ai
  Back-end/app.js
  Back-end/controllers/adminController.js
  Back-end/controllers/categoriasController.js
  Back-end/controllers/usuarioController.js
  Back-end/migrations/20220716140132-create-usuario.js
  Back-end/migrations/indexController.js
  Back-end/models/anime.js
  Back-end/models/comentarios.js
  Back-end/models/descricao.js
  Back-end/models/post.js
  Back-end/models/usuario.js
  Back-end/package-lock.json
  Back-end/package.json
  Back-end/routes/adminRoutes.js
  Back-end/routes/cadastro.js
  Back-end/routes/categorias.js
  Back-end/routes/editarPerfil.js
  Back-end/routes/index.js
  Back-end/routes/login.js
  Back-end/routes/usuarioRoutes.js
  Back-end/routes/vips.js
Labels: documentation, enhancement

#93 arrumando cards da page about
  animepedia/public/fonts/Ubuntu-Bold.ttf
  animepedia/public/images/art.jpg
  animepedia/public/images/comunidade.jpg
  animepedia/public/images/fanart.jpg.crdownload
  animepedia/public/images/manga.jpg
  animepedia/public/images/mangas.jpg
  animepedia/public/sass/indexStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardAbout.tsx
  animepedia/src/ui/components/sobre/pageSobre.tsx
Labels: documentation, enhancement

#96 feat: finalizando pagina sobre
  animepedia/public/images/fanart.jpg.crdownload
  animepedia/public/sass/indexStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardAbout.tsx
  animepedia/src/ui/components/forms/formContato.tsx
  animepedia/src/ui/components/sobre/pageSobre.tsx
Labels: documentation, enhancement

#97 feat: finalizando pagina politica privacidade e termos de uso
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/[lc]/privacidade.tsx
  animepedia/src/pages/[lc]/termos.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/footer/footer.tsx
  animepedia/src/ui/components/privacidade/politicaPrivacidade.tsx
  animepedia/src/ui/components/termosDeUso/termosUso.tsx
Labels: documentation, enhancement

#98 Feat/news
  Back-end/app.js
  Back-end/bin/www
  Back-end/controllers/usuarioController.js
  Back-end/middlewares/auth.js
  Back-end/migrations/20220716140132-create-usuarios.js
  Back-end/models/usuario.js
  Back-end/models/usuarios.js
  Back-end/package.json
  Back-end/routes/usuarioRoutes.js
  Back-end/server.js
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/src/data/hooks/pages/login/useLogin.ts
  animepedia/src/data/services/ApiService.jsx
  animepedia/src/data/services/ApiService.ts
  animepedia/src/pages/[lc]/login.tsx
  animepedia/src/pages/_app.tsx
  animepedia/src/ui/components/forms/formLogin.jsx
  animepedia/tsconfig.json
Labels: enhancement

#99 feat: adicionando editar perfil
  animepedia/public/images/hinata.jpg
  animepedia/public/sass/_custom_colors.scss
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/[lc]/editar.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/header/headerLogado.tsx
  animepedia/src/ui/components/perfil/editarPerfil.tsx
Labels: documentation, enhancement

#100 feat: add page editar perfil e favoritos
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/[lc]/favoritos.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardFavoritos.tsx
  animepedia/src/ui/components/card/cardGrid.tsx
  animepedia/src/ui/components/favoritos/PageFavoritos.tsx
  animepedia/src/ui/components/header/headerLogado.tsx
  animepedia/src/ui/components/perfil/editarPerfil.tsx
Labels: documentation, enhancement

#102 feat: add page admin
  animepedia/public/sass/indexStyle.scss
  animepedia/public/sass/style.scss
  animepedia/public/sass/styles.scss
  animepedia/src/pages/[lc]/admin.tsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/Admin/index.tsx
Labels: documentation, enhancement

#103 feat: retirando api do projeto
  animepedia/src/data/hooks/pages/login/useLogin.ts
Labels: enhancement

#106 feat: ajeitando forms metodo post
  animepedia/src/pages/[lc]/admin.jsx
  animepedia/src/ui/components/Admin/index.jsx
  animepedia/src/ui/components/Admin/index.tsx
  animepedia/src/ui/components/Cadastro/index.jsx
  animepedia/src/ui/components/Container/criarCategoria.jsx
  animepedia/src/ui/components/Container/criarPost.jsx
  animepedia/tsconfig.json
Labels: documentation, enhancement

#107 feat: add hover
  animepedia/public/sass/indexStyle.scss
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/card/cardGroups.tsx
Labels: documentation, enhancement

#108 feat: ajeitando form
  animepedia/src/pages/[lc]/generos.jsx
  animepedia/src/pages/[lc]/lancamento.jsx
  animepedia/src/pages/[lc]/populares.jsx
  animepedia/src/ui/components/Cadastro/index.jsx
  animepedia/src/ui/components/Container/criarCategoria.jsx
  animepedia/src/ui/components/Container/criarPost.jsx
  animepedia/src/ui/components/anime/Lancamento.jsx
  animepedia/src/ui/components/anime/Populares.jsx
  animepedia/src/ui/components/anime/generos.jsx
  animepedia/src/ui/components/header/header.tsx
Labels: documentation, enhancement

#109 feat: add paginas de mangá
  animepedia/src/pages/[lc]/generoManga.jsx
  animepedia/src/pages/[lc]/lancamentoManga.jsx
  animepedia/src/pages/[lc]/manga.jsx
  animepedia/src/pages/[lc]/popularesManga.jsx
  animepedia/src/ui/components/Manga/Generos.jsx
  animepedia/src/ui/components/Manga/Lancamento.jsx
  animepedia/src/ui/components/Manga/Populares.jsx
  animepedia/src/ui/components/Manga/index.jsx
  animepedia/src/ui/components/header/header.tsx
Labels: documentation, enhancement

#111 feat: add page posts
  animepedia/public/sass/indexStyle.scss
  animepedia/src/pages/[lc]/post.jsx
  animepedia/src/styles/bundle.css
  animepedia/src/ui/components/Post/index.jsx
  animepedia/tsconfig.json
  package-lock.json
Labels: documentation, enhancement

#112 feat: add multer
  animepedia/package-lock.json
  animepedia/package.json
  animepedia/src/ui/components/Cadastro/index.jsx
  animepedia/src/ui/components/Container/criarCategoria.jsx
  animepedia/src/ui/components/Container/criarPost.jsx
  animepedia/src/ui/components/Perfil/editarPerfil.jsx
Labels: documentation, enhancement

#113 feat: add map
  animepedia/src/ui/components/Container/criarCategoria.jsx
  animepedia/src/ui/components/Manga/index.jsx
  animepedia/src/ui/components/anime/generos.jsx
  animepedia/src/ui/components/anime/index.jsx
Labels: documentation, enhancement

#114 Feature/frontend
  animepedia/src/ui/components/Manga/index.jsx
  animepedia/src/ui/components/anime/index.jsx
Labels: documentation, enhancement

#115 feat: add use effect e use state
  animepedia/src/ui/components/Manga/Generos.jsx
  animepedia/src/ui/components/Manga/Lancamento.jsx
  animepedia/src/ui/components/Manga/Populares.jsx
  animepedia/src/ui/components/anime/Lancamento.jsx
  animepedia/src/ui/components/anime/Populares.jsx
  animepedia/src/ui/components/anime/generos.jsx
Labels: documentation, enhancement

#116 feat: add use effect e use state
  animepedia/src/ui/components/Index/sliderIndex.jsx
Labels: documentation, enhancement
